version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-202-22-140.compute-1.amazonaws.com
            database: deaf37mhfutt43
            schema: management
            user: zlfwfvwqaeuqhr
            password: c6d6bd31ac46f8f4ae0ab5ddc4bfabaf491d12a7276d7d29cfa9daf97e0f6297
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true