version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-34-239-241-25.compute-1.amazonaws.com
            database: dbdmsjup0h1ir7
            schema: management
            user: ocumyzntxirgta
            password: 457a146adc597bf283e071a1d67fd405dcebed0886196bb2b3a75f6f58a33e5c
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: false